Adding short note on multiple users' usage
aiidateam/aiida-core pull request #4109
Opened 2020-05-25 11:29 UTC by giovannipizzi

This will be extended in the future when better multiuser support will be available

Fixes #4005

2020-05-25 12:01 UTC, sphuber requested changes
Thanks @giovannipizzi . The way you describe it here, we are essentially saying that we don't support multi-user configurations. Having each user install their own instance does not count. If that is what we want to do, I think we should make this more explicit. Something like the following as a first sentence. "Setups with multiple users for a single AiiDA instance is currently not supported".

That being said, even though we don't have a formal multi-user system in place, there are certain ways to have some kind of multiple user setups. I feel it might still be useful to note these here, albeit with a fat disclaimer of the relevant caveats. Would you agree?

2020-05-25 20:42 UTC, giovannipizzi commented on docs/source/howto/installation.rst
> +   Therefore, always use UUIDs when you are referring to AiiDA nodes that you are not going to use only in your AiiDA installation.
Ok

2020-05-25 20:46 UTC, giovannipizzi commented
I have accepted the suggestion, and removed the note on UUIDs vs PKs.
Instead, as discussed, for now I will not expand on ways to have multiple user-setup as I never tested them, or some of the other options might not guarantee enough security. We can always extend this section later, if we want.

This is ready to be reviewed again (and merged - I have rebased).

2020-05-26 06:37 UTC, sphuber requested changes
Thanks @giovannipizzi some minor changes and then I will merge this

2020-05-26 06:37 UTC, sphuber commented on docs/source/howto/installation.rst
> +Setups with multiple users for a single AiiDA instance is currently not supported.
```suggestion
Setups with multiple users for a single AiiDA instance are currently not supported.
```

2020-05-26 06:37 UTC, sphuber commented on docs/source/howto/installation.rst
> +Instead, each AiiDA user should install AiiDA in an Unix/Windows account on their own computer or workstation.
```suggestion
Instead, each AiiDA user should install AiiDA in a Unix/Windows account on their own computer.
```

2020-05-26 06:37 UTC, sphuber commented on docs/source/howto/installation.rst
> +Under this account it is possible to configure all the credentials to connect to remote computers.
```suggestion
Under this account it is possible to configure all the credentials necessary to connect to remote computers.
```

2020-05-26 06:37 UTC, sphuber commented on docs/source/howto/installation.rst
> +Data can be shared using :ref:`AiiDA's export and import functionality <how-to:data:share>`.
```suggestion
Data can be shared between instances using :ref:`AiiDA's export and import functionality <how-to:data:share>`.
```

2020-05-26 08:19 UTC, csadorf reviewed
This looks fine and I agree with @sphuber 's comments. I'll approve once those comments are addressed and the merge conflict is resolved.

2020-05-26 08:22 UTC, giovannipizzi commented
Should be done now

2020-05-26 09:21 UTC, csadorf approved these changes

2020-05-26 09:21 UTC, csadorf commented
@sphuber Please merge at your discretion.

2020-05-26 09:30 UTC, sphuber approved these changes

2020-05-26 09:30 UTC, merged