Templatereplacer: fix files input namespace + add tests
aiidateam/aiida-core pull request #4348
Opened 2020-09-02 15:51 UTC by ramirezfranciscof

The `files` input namespace of the `TemplatereplacerCalculation` was not dynamic (so it was basically an unusable namespace with no inputs in it). This is a quick fix for that. Additionally, I have added a test for all of its basic functionalities and a test specifically for said namespace.

2020-09-02 21:08 UTC, sphuber commented
@ramirezfranciscof I think you may have used an incorrect branch because this seems to include two unrelated commits.

2020-09-03 11:00 UTC, ramirezfranciscof commented
@sphuber There, I fixed that, rebased and all test pass. Thanks for the heads up, I promise I will eventually make a good PR from the first push (⌒_⌒;)

2020-09-03 13:26 UTC, sphuber requested changes
Thanks @ramirezfranciscof just a minor simplification

2020-09-03 13:26 UTC, sphuber commented on tests/calculations/test_templatereplacer.py
> +    file1_node = orm.SinglefileData(file=file1_handle.strpath)
```suggestion
    file1_node = orm.SinglefileData(io.StringIO('Content of file 1'))
```

2020-09-03 13:26 UTC, sphuber commented on tests/calculations/test_templatereplacer.py
> +    file2_node = orm.SinglefileData(file=file2_handle.strpath)
```suggestion
file2_node = orm.SinglefileData(io.StringIO('Content of file 2'))
```

2020-09-04 07:47 UTC, sphuber commented
Sorry @ramirezfranciscof that should have been `io.BytesIO(b'some_string')`. I will correct it. Anyway need to rebase it

2020-09-04 08:13 UTC, ramirezfranciscof commented
Ah, no problem, I didn't notice either! For me its ready to merge.

2020-09-04 08:16 UTC, sphuber approved these changes

2020-09-04 08:16 UTC, merged