Add info on export format to internals section
aiidateam/aiida-core pull request #4467
Opened 2020-10-19 11:23 UTC by ramirezfranciscof

2020-10-19 12:15 UTC, giovannipizzi commented
Hi Francisco, can you also remove the old content from the previous source (I think it was in `import_export/main.rst`), either only the content you moved, or all the file, so at the end we know what we didn't migrate yet?

2020-10-19 12:28 UTC, ramirezfranciscof commented
Ok; my original idea was that I could anyways wait until all associated new content was merged and then delete all files in a given "remove" issue at once (seemed better than have each one decide what part to remove of the files), but from the message in the slack and this comment I assume you prefer that each deletes the part that each copies.

PD: It seems that we are having a BIG bottleneck in the tests. Maybe we should discuss if there is something that can be done about this in the afternoon meeting...

2020-10-19 15:48 UTC, ramirezfranciscof commented
I updated all references to "export" into "AiiDA archive". There are some inconsitencies due to the references in the actual code (`export_version` inside the `metadata.json`, or the command being `verdi export migrate`) but I don't think there is much I can do about those.

Now should be ready to review @giovannipizzi @sphuber

2020-10-19 17:23 UTC, giovannipizzi requested changes
Some minor suggestions.

Also, please add a redirect from the old URL describing the data storage to this new URL.

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +An AiiDA archive file is a ``.zip`` or ``.tar.gz`` file with the following content:
```suggestion
An AiiDA archive file is a file usually ending with extension ``.aiida``, typically compressed in ``.zip`` or ``.tar.gz`` format, with the following content:
```

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +.. _metadata-json:
You might want to use a longer reference name using the full prefix of where this is - these are global labels. So e.g. something like `_internal_architecture:orm:archive:metadata-json:`

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +The entities that are exported are mentioned in *unique_identifiers* with their respective unique identifiers.
```suggestion
The entities that are exported are mentioned in `unique_identifiers` with their respective unique identifiers.
```

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +At the beginning of the file, we see the version of the archive file (under `export_version`) and the version of the AiiDA code.
```suggestion
At the beginning of the file, we see the version of the archive file (under ``export_version``) and the version of the AiiDA code.
```

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +At the beginning of the file, we see the version of the archive file (under `export_version`) and the version of the AiiDA code.
I think here and below sometimes single backpacks are used, sometimes stars etc - I suggest using double backticks everywhere we refer to a literal string (e.g. the key of one of the JSON files) - I didn't put a comment on each of them

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +The entities that are exported are mentioned in *unique_identifiers* with their respective unique identifiers.
Same for the fields below

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +.. _data-json:
As above

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +For every link the UUIDs (universal unique identifiers) of the connected nodes, as well as the name of the link, are mentioned.
```suggestion
For every link the UUIDs of the connected nodes, as well as the name of the link, are mentioned.
```
(I think people should know by now what the UUID of a node is)

2020-10-19 17:23 UTC, giovannipizzi commented on docs/source/internals/data_storage.rst
> +This ensuries that the archive files are cross-backend compatible.
```suggestion
This ensures that the archive files are compatible between different actual database backend/schema implementations (e.g. Django, SQLAlchemy, ...).
```

2020-10-20 07:45 UTC, ramirezfranciscof commented
@giovannipizzi for now the redirection works for the full page (so `import_export/main.html --> internals/data_storage.html`), I have just asked if it was possible to do section redirection (`import_export/main.html#export-file-format --> internals/data_storage.html#aiida-archive-format`) which is the link that you originally wanted to fix.

2020-10-20 07:52 UTC, ramirezfranciscof commented
For which the answer is that apparently this can't be done, so I guess this is the best we can do.

2020-10-20 10:42 UTC, giovannipizzi approved these changes
Thanks!

2020-10-20 11:02 UTC, merged