Dependencies: update minimum version for `notebook>=6.1.5`
aiidateam/aiida-core pull request #4593
Opened 2020-11-27 18:11 UTC by sphuber

Lower versions suffer from vulnerability `GHSA-c7vm-f5p4-8fqh`.

2020-11-27 18:15 UTC, csadorf requested changes
The specs in the `requirements/` files should be pinned.

2020-11-27 18:18 UTC, sphuber commented
> The specs in the `requirements/` files should be pinned.

There are some other dependencies in those files that use the compatibility operator `~=`. Do you want me to update those in this PR as well?

2020-11-27 18:20 UTC, csadorf commented
> > The specs in the `requirements/` files should be pinned.
> 
> There are some other dependencies in those files that use the compatibility operator `~=`. Do you want me to update those in this PR as well?

Yes, please. These files are used to install our test environments, so they should be pinned.

2020-11-27 22:21 UTC, sphuber commented
@csadorf I have updated the requirement files. Pinning `pamqp` revealed a problem with the original requirements in the `setup.json` which declared `~-2.0` but in fact we need `~=2.3` at the least. I included this in this PR, even though that wasn't the original intention.

2020-11-30 16:28 UTC, csadorf requested changes

2020-11-30 16:28 UTC, csadorf commented on setup.json
> +            "notebook~=6.0,>=6.1.5"
Technically valid, but I think this would be better:
```suggestion
            "notebook~=6.1,>=6.1.5"
```

2020-12-01 09:58 UTC, csadorf approved these changes

2020-12-01 10:18 UTC, merged