cli: notify users of runner usage
aiidateam/aiida-core pull request #4663
Opened 2021-01-14 16:04 UTC by ltalirz

The extra query performed in `verdi process list` to get the load on the
daemon runners is slow - and usually results in no output for the user.
This PR at least lets the user know what is being queried (which also may be useful
to monitor runner load).

2021-01-14 23:02 UTC, ltalirz commented
Not sure why the tests failed... didn't change docs + this should not be backend-specific behavior

2021-01-15 07:58 UTC, sphuber requested changes
Thanks @ltalirz . Fine by me, would just not add the case where daemon is not running as that is already covered in `verdi process list` itself.

2021-01-18 12:19 UTC, ltalirz commented
> Thanks @ltalirz . Fine by me, would just not add the case where daemon is not running as that is already covered in `verdi process list` itself.

Thanks - I've pulled out that check from the previous function and now call the worker query only when needed.

2021-01-18 12:27 UTC, ltalirz commented on docs/source/reference/command_line.rst
>                                        ARCHIVES for importing
Note: I first removed these changes again but then noticed that they also appear on the [CI pre-commit check](https://github.com/ltalirz/aiida-core/runs/1721347516?check_suite_focus=true) - some updated version perhaps?

2021-01-27 18:29 UTC, ltalirz commented
@sphuber Now that the print is gone when no daemon is running, the test checking its output fails.

What do you think is the best approach here - fake a daemon or move this test to the daemon tests?
I'm wondering whether one could fake a running daemon by running things inside a `with` block that creates the pid file, something along the lines of 

```python
with open(get_daemon_client().circus_port_file, 'w', encoding='utf8') as fhandle:
   fhandle.write(123)

   test..
```

Perhaps there are cleaner approaches

2021-08-12 21:41 UTC, sphuber commented
> Perhaps there are cleaner approaches

The typical way is to simply monkeypatch the `DaemonClient.is_daemon_running` property to always return `True`. This is made easy using `pytest`, so I have migrated the test to `pytest` and it should now work. Let me know if you also are happy with the changes, then I will approve and merge @ltalirz

2021-08-13 05:51 UTC, ltalirz reviewed
thanks @sphuber !

2021-08-13 07:46 UTC, sphuber approved these changes

2021-08-13 07:47 UTC, merged