Implement 'identify-constraints' command for dependency_management
aiidateam/aiida-core pull request #4852
Opened 2021-04-07 17:37 UTC by csadorf

Utility function to analyze the package dependencies and identify
packages where the latest release is no longer compatibility with our
constraints.

2021-04-07 17:42 UTC, csadorf commented
This is the current output for all extras:

```bash
$ ./utils/dependency_management.py identify-constraints all
seekpath>=1.9.3,~=1.9 2.0.1
packaging==20.3 20.9
wrapt~=1.11.1 1.12.1
django~=2.2 3.2
pyyaml~=5.1.2 5.4.1
docutils==0.15.2 0.17
astroid<2.5 2.5.2
pylint-django<2.4.0,>=2.0 2.4.2
coverage<5.0 5.5
pylint~=2.5.0 2.7.4
aldjemy~=0.9.1 1.0.0
pytz~=2019.3 2021.1
mypy==0.790 0.812
pymysql~=0.9.3 1.0.2
pydata-sphinx-theme~=0.4.0 0.5.2
pamqp~=2.3 3.0.1
bpython~=0.18.0 0.21
sqlalchemy~=1.3.10 1.4.6
sphinx~=3.2.1 3.5.3
```

It's not that bad without extras:

```bash
$ ./utils/dependency_management.py identify-constraints
pamqp~=2.3 3.0.1
wrapt~=1.11.1 1.12.1
django~=2.2 3.2
aldjemy~=0.9.1 1.0.0
pyyaml~=5.1.2 5.4.1
pytz~=2019.3 2021.1
sqlalchemy~=1.3.10 1.4.6
```

2021-04-07 17:46 UTC, csadorf commented
We still need to think about whether we want to also introduce some kind of auxiliary procedure for when this script is executed. Here are some procedures I could think of: 

1. Run it as part of the CI workflow and warn when there are incompatibilites (unless explicitly ignored or so).
2. Run this as part of the CI workflow and in addition to warnings fail when a dependency is very outdated (more than one major version, latest supported release is more than 1 year old compared to the latest supported release).
3. Run this manually at certain points in time (e.g. before a minor or major release) and try to loosen some constraints.

2021-05-04 11:05 UTC, ltalirz requested changes
thanks @csadorf !

Looks all good to me - I would just suggest to change the name of the command since it was not obvious to me that it would actually check against the PyPI registry to see which constraints lead to outdated packages being installed.


> We still need to think about whether we want to also introduce some kind of auxiliary procedure for when this script is executed. Here are some procedures I could think of:
> 1. Run it as part of the CI workflow and warn when there are incompatibilites (unless explicitly ignored or so).
> 1. Run this as part of the CI workflow and in addition to warnings fail when a dependency is very outdated (more than one major version, latest supported release is more than 1 year old compared to the latest supported release).
> 1. Run this manually at certain points in time (e.g. before a minor or major release) and try to loosen some constraints.

Good point. To me the ideal solution would be (1.) to run it as part of the nightly builds and notify the dependency manager of outdated dependencies. 
If that is not straightforward to implement variant 3. would also be fine.

Some more thoughts on this
 * Checking compatibility with newly released dependencies and removing unnecessary version constraints is a good thing, so I don't see a reason to limit this to major/minor releases only
 * This applies as long as we are talking only about relaxing dependency constraints, not tightening them (e.g. by removing compatibility with older versions of the dependency). The latter may require a major or perhaps minor release (with some leeway on a case-by-case basis)

2021-05-04 11:22 UTC, chrisjsewell commented
Yeh looking good to cheers @csadorf.
One thought, `dependency_management.py` is getting pretty big these days and is relatively generic. It feels like at some point we could extract this into a small seperate package to install
(rather this ever-growing `pip install packaging==20.3 click~=7.0 pyyaml~=5.1 tomlkit requests==2.25.1` lol)

2021-05-05 08:56 UTC, csadorf commented
> Yeh looking good to cheers @csadorf.
> One thought, `dependency_management.py` is getting pretty big these days and is relatively generic. It feels like at some point we could extract this into a small seperate package to install
> (rather this ever-growing `pip install packaging==20.3 click~=7.0 pyyaml~=5.1 tomlkit requests==2.25.1` lol)

Good idea, would you also suggest to put it on PyPI or just vendor it here as a local package? If it's the former, any idea for a name? Just `dependency-manager` or something more fun?

2021-08-03 08:36 UTC, csadorf commented on utils/dependency_management.py
> +    """Identify dependency constraints
I'll keep that short so that the `--help` text remains visible on screen.

2021-08-03 08:37 UTC, csadorf commented on utils/dependency_management.py
> +    This command will analyze the current dependencies and compared them against
fixed

2021-08-03 08:42 UTC, csadorf commented on utils/dependency_management.py
> +def identify_constraints(extras, pre_releases):
applied

2021-08-03 09:02 UTC, csadorf commented
@ltalirz I would like to merge this and introduce any updates to the CI workflow in a separate PR.

2021-08-03 09:56 UTC, ltalirz approved these changes
looks good to me

2021-08-03 10:19 UTC, merged