CI: use `postgres-12` since update to Ubuntu Focal 20.04
aiidateam/aiida-core pull request #4860
Opened 2021-04-16 14:11 UTC by mbercx

The CI configuration uses `ubuntu-latest` which recently became Ubuntu
Focal Fossa (20.04) which no longer has `postgres-10` available, but
instead provides `postgres-12`.

2021-04-16 14:13 UTC, mbercx commented
Just noticed that my tests were failing in #4761:

https://github.com/aiidateam/aiida-core/pull/4761/checks?check_run_id=2362353306#step:5:63

Had the same issue for `aiida-quantumespresso`, see:

https://github.com/aiidateam/aiida-quantumespresso/pull/674

2021-04-16 14:41 UTC, greschd commented
Why don't we just remove the version and install ``postgresql`` instead?

2021-04-16 15:19 UTC, csadorf commented
@mbercx I like @greschd ' suggestion, can you try that?

2021-04-16 15:20 UTC, csadorf requested changes
Generally, I'd suggest that we fix all dependencies in our CI workflows, but in this case I'm inclined to follow @greschd ' suggestion to install the default version. At the very least we should do that for the `test-install` workflow which should as closely as possible resemble our installation instructions on the docs.

2021-04-17 09:51 UTC, mbercx commented
Thanks for the comments @greschd and @csadorf! Have made the suggested adjusment 👍

2021-04-19 08:09 UTC, csadorf approved these changes

2021-04-19 08:10 UTC, merged