fix verdi computer show tab completion
aiidateam/aiida-core pull request #4962
Opened 2021-05-26 09:15 UTC by unkcpz

Got the following error when doing `verdi computer show <tab>`. This is a quick fix but just thinking when this change made in `DbComputer`, maybe other places also need to be take care of?

```
Traceback (most recent call last):                                                                                      
  File "/home/unkcpz/Projects/python-code/aiida_core/aiida/orm/implementation/querybuilder.py", line 399, in get_column 
    return getattr(alias, colname)                                                                                      
  File "/home/unkcpz/miniconda3/envs/aiida-core-dev/lib/python3.8/site-packages/sqlalchemy/orm/util.py", line 506, in __
getattr__                                                                                                               
    attr = getattr(target, key)                                                                                         
AttributeError: type object 'DbComputer' has no attribute 'name'
...
...
  File "/home/unkcpz/Projects/python-code/aiida_core/aiida/orm/querybuilder.py", line 1225, in _add_to_projections
    entity_to_project = self._get_projectable_entity(alias, column_name, attr_key, cast=cast)
  File "/home/unkcpz/Projects/python-code/aiida_core/aiida/orm/querybuilder.py", line 1199, in _get_projectable_entity
    entity = self._impl.get_column(column_name, alias)
  File "/home/unkcpz/Projects/python-code/aiida_core/aiida/orm/implementation/querybuilder.py", line 401, in get_column
    raise ValueError(
ValueError: name is not a column of aliased(DbComputer)
Valid columns are:
id
uuid
label
hostname
description
scheduler_type
transport_type
metadata
```

2021-05-26 09:31 UTC, sphuber requested changes
Thanks @unkcpz . The change of `DbComputer.name` to `DbComputer.label` was done in #4882 . It should have updated all other places in the code that still used `name` but this one was clearly missed and it is not tested. It would be great if you could add a quick test for it. Note that I think therefore we should also project on `label` instead of the hostname, because that is essentially what was being projected originally.

2021-05-26 09:31 UTC, sphuber commented on aiida/cmdline/params/types/computer.py
> +        return [(option, '') for option, in self.orm_class_loader.get_options(incomplete, project='hostname')]
```suggestion
        return [(option, '') for option, in self.orm_class_loader.get_options(incomplete, project='label')]
```

2021-05-26 10:42 UTC, unkcpz commented
Thanks @sphuber. The test added and also refactoring the unit test to use pytest.

2021-05-26 10:59 UTC, unkcpz commented
Well, seems run into pre-commit pylint warnings. Do we need to exclude `tests/` in pre-commit-pylint?

2021-05-26 11:24 UTC, sphuber requested changes
Thanks a lot for the test and refactoring @unkcpz  . The tests should also be linted so it should not be added to the exclude list. The errors are easy to address though. I made three suggestions that show how to do it. Just the one of unused variables you should apply to the other locations in the code that pylint mentioned

2021-05-26 11:24 UTC, sphuber commented on tests/cmdline/params/types/test_computer.py
>  """Tests for the `ComputerParamType`."""
# pylint: disable=redefined-outer-name

2021-05-26 11:24 UTC, sphuber commented on tests/cmdline/params/types/test_computer.py
> +def setup_computers(clear_database_before_test):
```suggestion
@pytest.mark.usefixtures('clear_database_before_test')
def setup_computers():
```

2021-05-26 11:24 UTC, sphuber commented on tests/cmdline/params/types/test_computer.py
> +    entity_01, entity_02, entity_03 = setup_computers
```suggestion
    entity_01, _, _ = setup_computers
```

2021-05-26 11:54 UTC, unkcpz commented
@sphuber thanks!  It should be all right this time.

2021-05-26 12:24 UTC, sphuber commented on tests/cmdline/params/types/test_computer.py
> +def setup_computers(clear_database_before_test):
Uhm, we do it in plenty of places with no problems. So I doubt that it is not possible. What makes you think that besides that PR you linked?

2021-06-02 08:02 UTC, sphuber approved these changes

2021-06-02 08:02 UTC, merged