Revise Docker image build:
aiidateam/aiida-core pull request #4997
Opened 2021-06-25 20:50 UTC by yakutovicha

* Build a new image on every PR (with caching).
* Test the functionality of the new image on every PR.
* Build a new image on every commit to develop/master branch and every
time a new tag is created (no caching).

2021-06-25 23:36 UTC, chrisjsewell commented on .github/workflows/build_and_test_docker_on_pr.yml
> +  [pull_request]
Don’t run on document only changes: paths-ignore: ['docs/**']

2021-06-28 07:38 UTC, yakutovicha commented on .github/workflows/build_and_test_docker_on_pr.yml
> +  [pull_request]
done.

2021-06-28 08:57 UTC, yakutovicha commented
An important thing to note: we need somebody to put their Dockerhub credentials in GitHub secrets: `DOCKER_USERNAME` and `DOCKER_TOKEN`. Who wants to be that somebody? Maybe @giovannipizzi?

2021-06-29 07:16 UTC, yakutovicha commented
> An important thing to note: we need somebody to put their Dockerhub credentials in GitHub secrets: `DOCKER_USERNAME` and `DOCKER_TOKEN`. Who wants to be that somebody? Maybe @giovannipizzi?

I added my own Docker Hub username and token. Feel free to change it.

2021-06-30 09:09 UTC, chrisjsewell requested changes
thanks @yakutovicha, just a minor nitpick

2021-06-30 09:09 UTC, chrisjsewell commented on .github/workflows/push_image_to_dockerhub.yml
> +      - 'v*'
```suggestion
      - "v[0-9]+.[0-9]+.[0-9]+*"
```

this is what we use for the other release workflow

2021-06-30 09:22 UTC, chrisjsewell approved these changes

2021-06-30 10:01 UTC, merged