Remove superfluous _validate from Data node
aiidateam/aiida-core pull request #5089
Opened 2021-08-19 15:55 UTC by ltalirz

The Data nodeclass overwrote the `_validate` function but
 (a) did no validation
 (b) included commented code that referenced a private git repository
 (c) returned `None` instead of `True`.

The outcommented code involved validation of the `source` attribute and
the referenced issue pointed out that the value of this attribute was
not officially standardized (potentially leading users to using it in
different ways).

Since there has not been validation of this field since 2015, it seems
safe to assume that it cannot be easily reintroduced at this point.

2021-09-01 08:06 UTC, ramirezfranciscof approved these changes
Hey @ltalirz ! Just one little comment but other than that this looks good to go for me, ping me if you need final approval once you rebase/update.

2021-09-01 08:06 UTC, ramirezfranciscof commented on aiida/orm/nodes/node.py
> +        and should usually call ``super()._validate()``!
Maybe this is obvious if you are used how the `super` works, but I'd still keep this clarification:

```suggestion
        and should usually call ``super()._validate()`` first!
```

or

```suggestion
        and should usually call ``super()._validate()`` at the beginning of it!
```

2021-09-01 08:16 UTC, ltalirz commented
thanks, done!

2021-09-01 08:47 UTC, ramirezfranciscof commented
Mmm strange i thought that would fix the CI doc problem. Do you understand what is wrong with this? I'll try compiling the docs locally.

2021-09-01 09:16 UTC, ramirezfranciscof requested changes

2021-09-01 09:16 UTC, ramirezfranciscof commented on aiida/orm/nodes/node.py
> +        Therefore, use :py:meth:`~aiida.orm.entities.Entity.get_attribute()` and similar methods that automatically
This fixes the problem locally for me.

```suggestion
        Therefore, use :py:meth:`~aiida.orm.entities.EntityAttributesMixin.get_attribute()` and similar methods that automatically
```

2021-09-02 12:38 UTC, ramirezfranciscof commented on aiida/orm/nodes/node.py
> +        read either from the DB or from the internal attribute cache.
Haha damn pyliny. Ok, I hope you don't mind if I just commit this and merge xD.

```suggestion
        Therefore, use :py:meth:`~aiida.orm.entities.EntityAttributesMixin.get_attribute()` and similar methods that
        automatically read either from the DB or from the internal attribute cache.
```

2021-09-02 12:39 UTC, ramirezfranciscof commented on aiida/orm/nodes/node.py
> +        read either from the DB or from the internal attribute cache.
(I changed this because pylint was complaining the line was too long)

2021-09-02 12:54 UTC, ltalirz commented
sure, please go ahead!

2021-09-02 13:22 UTC, ramirezfranciscof approved these changes
All good gogogo =P

2021-09-02 13:24 UTC, merged