👌 IMPROVE: Tar file archive migration performance
aiidateam/aiida-core pull request #5275
Opened 2021-12-15 08:49 UTC by chrisjsewell

Tar files do not allow performant single file streaming,
and so the file is fully extracted to disk,
before streaming to the new (zip file) archive.

2021-12-17 11:01 UTC, unkcpz requested changes
@chrisjsewell Thanks for the quick fix. I make the test on the tar achieve and it works great! Just a minor request from my side. And for the `base_parts` change, I have to admit I am not familiar with this part, so maybe @ramirezfranciscof can have another eye on this?

2022-01-15 08:36 UTC, chrisjsewell commented on aiida/tools/archive/implementations/sqlite/migrations/legacy_to_new.py
> +                    parts = subpath.parts[base_parts:]
If we are inside an archive, then the path is always relative to the archive (`base_parts = 0`), but if we are inside a file system then the path may be absolute, and we want to get back to the relative path.

2022-01-15 08:37 UTC, chrisjsewell commented
Ok, as it works I'm gonna merge 😄

2022-01-15 09:07 UTC, unkcpz approved these changes
Cool! Thanks @chrisjsewell

2022-01-15 09:07 UTC, merged

2022-01-15 09:09 UTC, chrisjsewell commented
Cheers!