CLI: fix shell completion of script for `verdi run`
aiidateam/aiida-core pull request #5430
Opened 2022-03-12 11:54 UTC by sphuber

When we moved to the built-in shell completion of `click==8.0` instead
of the external `click_completion`, the script argument of `verdi run`
was no longer auto-completed. The reason is that `click` does not
autocomplete files for the `STRING` type.

The parameter type is changed to `click.Path`, which not only fixes the
problem of auto-completion, it also provides automatic validation by
making sure if it is an existing file and not a directory. This allows
to simplify the logic in the command body significantly as well as we no
longer need to handle the `IOError` of unreadable files manually.

2022-03-12 12:10 UTC, sphuber commented
@unkcpz I took the start of your fix and fleshed it out a bit to fix the implementation. I then also added a fix on top to reinstate shell completion for relative filepaths. So I decided to make a separate PR, hope you don't mind.

2022-03-12 12:21 UTC, unkcpz commented
@sphuber absolutely not mind 😄. I'll have a review and test the change later. 
After your change, the `~` and `.` relative path is working for the `verdi run` but still not for all other param type, correct?

2022-03-14 13:28 UTC, unkcpz requested changes
@sphuber thanks for the fix. Looks all good, only one minor thing can be added I think.

2022-03-14 13:28 UTC, unkcpz commented on aiida/cmdline/commands/cmd_verdi.py
> +    return not value[0].isalnum() and value[0] not in ['/', '.', '~']
```suggestion
    return not value[0].isalnum() and value[0] not in ['/', '.', '~', '$']
```

I think should also add to escape for `$HOME` and `$PWD` here.

2022-03-14 13:59 UTC, merged