♻️ REFACTOR: `NodeRepositoryMixin` -> `NodeRepository`
aiidateam/aiida-core pull request #5442
Opened 2022-03-14 12:19 UTC by chrisjsewell

This is currently based on top of #5439

Similar to #5439, it moves the node's attributes methods to a separate "namespace", in a back compatible manner, and is another step towards https://github.com/aiidateam/aiida-core/issues/4976#issuecomment-1066264580: removing another 10 methods.

the following deprecations are made:

```python
    _deprecated_attr_methods = {
        'attributes': 'all',
        'get_attribute': 'get',
        'get_attribute_many': 'get_many',
        'set_attribute': 'set',
        'set_attribute_many': 'set_many',
        'reset_attributes': 'reset',
        'delete_attribute': 'delete',
        'delete_attribute_many': 'delete_many',
        'clear_attributes': 'clear',
        'attributes_items': 'items',
        'attributes_keys': 'keys',
    }
```

e.g. `Node.get_attribute` to `Node.attrs.get`

Ideally, it may have been preferable to have `Node.attributes.get` but, as you can see, `Node.attributes` is already one of the methods we need to deprecate, so that is not possible, without backward-incomatible changes.

It also actually fixes a bug with the `Sealable` mixin of `ProcessNode`, whereby it only overrode `set_attribute` and `delete_attribute`, to change mutability behaviour, but not any other mutation methods, like `set_attribute_many`, etc

2022-04-07 08:03 UTC, sphuber requested changes
Thanks @chrisjsewell , just some minor things.

2022-04-07 09:57 UTC, chrisjsewell commented on aiida/orm/nodes/attributes.py
> +        self._backend_entity = node.backend_entity
done

2022-04-07 12:50 UTC, sphuber commented
@chrisjsewell just to let you know that tests are failing, so cannot merge yet

2022-04-07 12:54 UTC, chrisjsewell commented on aiida/orm/nodes/attributes.py
> +        return key in self._backend_entity.attributes
re-instated because there is actually a test, hence why they were failing

2022-04-07 12:59 UTC, chrisjsewell commented on aiida/orm/nodes/attributes.py
> +        return key in self._backend_entity.attributes
Note @sphuber, it's my intention to look into making attributes and extras a subclass of `MutableMapping` (https://docs.python.org/3/library/collections.abc.html?highlight=mutablemapping#collections-abstract-base-classes), which would actually remove this method.

But this change is just additive, i.e. is just adding extra methods and not breaking anything. So don't want to hold up this initial re-structuring with it

2022-04-07 16:28 UTC, sphuber commented
You forgot to apply the `backend_entity` -> `backend_node` in `__contains__` I think @chrisjsewell

2022-04-07 17:09 UTC, chrisjsewell commented on aiida/orm/nodes/attributes.py
> +        return key in self._backend_entity.attributes
```suggestion
        return key in self._backend_node.attributes
```

2022-04-07 17:09 UTC, chrisjsewell commented
> You forgot to apply the backend_entity -> backend_node in __contains__ I think @chrisjsewell

Third times a charm 🤞

2022-04-07 17:33 UTC, chrisjsewell commented
All tests passing @sphuber

2022-04-07 20:22 UTC, sphuber requested changes
There are still uses of the deprecated methods:
```
 tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_complex.py:181: AiidaDeprecationWarning: `Dict.attributes` is deprecated, use `Dict.base.attributes.all` instead. (this will be removed in v3)
    item['param']['*'].attributes,

tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_complex.py:186: AiidaDeprecationWarning: `CalculationNode.attributes` is deprecated, use `CalculationNode.base.attributes.all` instead. (this will be removed in v3)
    item['calc']['*'].attributes,

tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
tests/tools/archive/test_complex.py::test_reexport
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_complex.py:187: AiidaDeprecationWarning: `ArrayData.attributes` is deprecated, use `ArrayData.base.attributes.all` instead. (this will be removed in v3)
    item['array']['*'].attributes,

tests/tools/archive/test_simple.py::test_calc_of_structuredata
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_simple.py:66: AiidaDeprecationWarning: `StructureData.attributes` is deprecated, use `StructureData.base.attributes.all` instead. (this will be removed in v3)
    for k in node.attributes.keys():

tests/tools/archive/test_simple.py::test_calc_of_structuredata
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_simple.py:66: AiidaDeprecationWarning: `CalcJobNode.attributes` is deprecated, use `CalcJobNode.base.attributes.all` instead. (this will be removed in v3)
    for k in node.attributes.keys():

tests/tools/archive/test_specific_import.py::test_cycle_structure_data
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_specific_import.py:124: AiidaDeprecationWarning: `CalculationNode.attributes` is deprecated, use `CalculationNode.base.attributes.all` instead. (this will be removed in v3)
    assert isinstance(calculation.attributes, dict)

tests/tools/archive/test_specific_import.py::test_cycle_structure_data
  /home/runner/work/aiida-core/aiida-core/tests/tools/archive/test_specific_import.py:125: AiidaDeprecationWarning: `CalculationNode.attributes` is deprecated, use `CalculationNode.base.attributes.all` instead. (this will be removed in v3)
    assert len(calculation.attributes) != 0

tests/tools/groups/test_paths.py::test_walk_nodes
  /home/runner/work/aiida-core/aiida-core/tests/tools/groups/test_paths.py:137: AiidaDeprecationWarning: `Data.attributes` is deprecated, use `Data.base.attributes.all` instead. (this will be removed in v3)
    assert [(r.group_path.path, r.node.attributes) for r in group_path.walk_nodes()] == [('a', {'i': 1, 'j': 2})]
```
Would be good to fix those, then we can merge

2022-04-07 20:24 UTC, chrisjsewell commented
> There are still uses of the deprecated methods:

How helpful are those deprecation warnings though 😉

2022-04-07 20:54 UTC, sphuber commented
> How helpful are those deprecation warnings though 😉

very 👍

2022-04-08 08:23 UTC, sphuber approved these changes
Thanks @chrisjsewell good to go

2022-04-08 08:32 UTC, merged