👌 IMPROVE: Move default user caching to `StorageBackend`
aiidateam/aiida-core pull request #5460
Opened 2022-03-22 08:56 UTC by chrisjsewell

Currently it is cached on the `UserCollection`,
but this means that, on profile switching,
it would return a user associated with the wrong backend instance.

2022-04-12 12:33 UTC, sphuber commented
Same as for #5461 if you add a quick test, we should merge this for the release since it is a known bug of the new profile switching

2022-04-25 12:40 UTC, chrisjsewell commented
@sphuber this is good to go

2022-04-25 13:04 UTC, sphuber requested changes

2022-04-26 09:45 UTC, sphuber approved these changes

2022-04-26 10:37 UTC, merged