Containerized code: double quotes setting of computer and code setup
aiidateam/aiida-core pull request #5478
Opened 2022-04-08 11:07 UTC by unkcpz

The PR is a part required for containerized code implementation (also for hyperqueue without hacky workaround to evaluate command-line variable by `$` properly) and is separated from https://github.com/aiidateam/aiida-core/pull/5250. It allows users to set up computer and code with an extra option `--use-double-quotes` to using double quotes for the command run line of job script.

2022-04-08 11:14 UTC, ltalirz commented
Thanks @unkcpz . At a high level, I'm just wondering: do we really need to push this choice to the user?

I.e. can't we be clever about using double quotes where necessary (if we detect some environment variable / ...)? This will be yet another option in the computer an code setup and I wonder whether people really need to care about this.

2022-04-08 11:21 UTC, unkcpz commented
Hi @ltalirz, yes ideally it should be intelligent enough to know when to use double quotes and not. But I think it is hard to decide by what criteria we escape it with double or single quotes. Setting it manually might be a safe way to keep the backward compatibility.

2022-04-08 18:06 UTC, sphuber requested changes
Thanks @unkcpz . Mostly minor comments, but one fundamental question: is the separate control of quoting in the `Code` and `Computer` necessary? And if so, why should the quoting for the `Computer` only apply to the argument before the executable and not any that follows, such as the input and output redirection?

2022-04-08 18:06 UTC, sphuber commented on aiida/schedulers/datastructures.py
> +    use_double_quotes: list[bool] = field(default_factory=list)
Please update the docstring:
```python
:param preprend_cmdline_params: list of command line arguments that are to be prepended to the executable.
:param use_double_quotes: list of two booleans. If true, use double quotes to escape command line arguments. The first
    value applies to `prepend_cmdline_params` and the second to `cmdline_params`.
```
What is `prepend_cmdine_params

2022-04-08 18:06 UTC, sphuber commented on aiida/engine/processes/calcjobs/calcjob.py
> +                              ] + (code_info.cmdline_params if code_info.cmdline_params is not None else [])
```suggestion
            cmdline_params = [this_code.get_execname()] + (code_info.cmdline_params or [])
```

2022-04-08 18:06 UTC, sphuber commented on aiida/cmdline/params/options/commands/computer.py
> +    is_eager=False,
This is the default and is not necessary
```suggestion
    is_eager=False,
```

2022-04-08 18:06 UTC, sphuber commented on aiida/cmdline/params/options/commands/code.py
> +    is_eager=False,
```suggestion
```

2022-04-08 18:06 UTC, sphuber commented on aiida/cmdline/params/options/commands/code.py
> +    prompt='Whether use double quotes for code cmdline params?',
```suggestion
    prompt='Escape CLI arguments in double quotes',
```

2022-04-08 18:06 UTC, sphuber commented on aiida/cmdline/params/options/commands/computer.py
> +    prompt='Whether use double quotes for prepend cmdline params?',
```suggestion
    prompt='Escape CLI arguments in double quotes',
```

2022-04-08 18:06 UTC, sphuber commented on aiida/cmdline/params/options/commands/code.py
> +    help='Whether the code executable parameters in script using the double quotes to escape.'
```suggestion
    help='Whether the executable and arguments of the code in the submission script should be escaped with single or double quotes.'
```

2022-04-08 18:06 UTC, sphuber commented on aiida/cmdline/params/options/commands/computer.py
> +    'script using the double quotes to escape.',
```suggestion
    help='Whether the command line arguments before the executable in the submission script should be escaped with single or double quotes.'
```

2022-04-19 16:14 UTC, unkcpz reviewed
@sphuber sorry for the delay of changes and reply, suffer from COVID last week. 

I implement most of your suggestions and also docstring of `use_double_quotes` of `JobTemplateCodeInfo`. 

> but one fundamental question: is the separate control of quoting in the Code and Computer necessary?

I think there are two reason to apply it independently: 1. it is more flexible and more possible for backward compatible if it can be controlled separately. 2. with initial containerized code implementation (the PR after this PR) the specific suffix for using containerized code is independent of `cmdline_params` parts of code and double quotes escape needed since I want to use `$PWD` to map working dir to directory where the inputs locate. While for the code part it can keep the same.

2022-04-20 10:00 UTC, sphuber commented on aiida/orm/nodes/data/code.py
> +        """
Same here. Don't see the changes.

2022-04-20 10:04 UTC, sphuber commented
Thanks @unkcpz . Hope you are feeling better. I noticed that you resolved a few comments that don't seem to actually have been addressed. At least I cannot see the changes of the suggestions I made. Also the tests and pre-commit are failing. Please fix those and update the branch.

2022-04-20 12:37 UTC, unkcpz commented
@sphuber sorry for the carelessness, I wrongly mix up commits and push to the actual container code implementation branch locally previously. Now it is rebased a bit and passes all the tests.

2022-04-22 09:43 UTC, sphuber approved these changes

2022-04-22 09:43 UTC, merged

2022-04-22 09:43 UTC, sphuber commented
Thanks @unkcpz !