Deprecate `Profile.repository_path`
aiidateam/aiida-core pull request #5516
Opened 2022-05-04 12:53 UTC by sphuber

Fixes #5513 

The `Profile.repository_path` was historically used to give the absolute
filepath to the file repository on the local file system. However, this
is a property of the storage backend and not all backends will have this.
So instead of being generic to all profiles, this should be a storage
specific setting.

The property is deprecated and the functionality is added to the new
`PsqlDosBackend.filepath_container`. This forwards to the same property
but on the `PsqlDostoreMigrator` that has the actual implementation. The
reason for this is because the migrator needs to get the repository
location in the `migrate` method, but that needs to remain a
classmethod. The alternative of having the migrator call the property on
the backend, would require the backend to be passed to the constructor
of the migrator, but this won't work as the migrator also needs to be
constructed in the constructor of the backend, leading to an infinite
regression.

There is a also  a slight difference in the implementation of the new
property. It returns the path of the disk object store container, which
is a subfolder of the original repository path. Old invocations of
`profile.repository_path` should therefore be replaced with
`backend.filepath_container.parent`.

Currently based on and blocked by #5496

2022-05-13 13:46 UTC, ramirezfranciscof commented
> The property is deprecated and the functionality is added to the new
> `PsqlDosBackend.filepath_container`. This forwards to the same property
> but on the `PsqlDostoreMigrator` that has the actual implementation. The
> reason for this is because the migrator needs to get the repository
> location in the `migrate` method, but that needs to remain a
> classmethod. The alternative of having the migrator call the property on
> the backend, would require the backend to be passed to the constructor
> of the migrator, but this won't work as the migrator also needs to be
> constructed in the constructor of the backend, leading to an infinite
> regression.

Mmm I understand the technical rationale behind this, but I feel like it is a bit obfuscating to have the implementation in the `PsqlDostoreMigrator`. This smells a bit like there is an improvement to be made in the interaction/interface between these two classes.

Probably this is not the ideal solution, but as an alternative that at least does not make the interweaving of these more complex, could we maybe pass the `filepath_container` as an argument for the `migrate` method and keep the implementation in `PsqlDosBackend`?

2022-05-13 15:20 UTC, sphuber commented
> Mmm I understand the technical rationale behind this, but I feel like it is a bit obfuscating to have the implementation in the `PsqlDostoreMigrator`. This smells a bit like there is an improvement to be made in the interaction/interface between these two classes.

That's what I tried initially. I tried to decouple this and make the migrator take an instance of the backend, but that won't work for now as the backend needs to be validated as it is constructed, for which it needs the migrator, and so there is a circular dependency. I discussed with @chrisjsewell and for now there is not better quick solution without a big refactoring of the backend/migrator.

> Probably this is not the ideal solution, but as an alternative that at least does not make the interweaving of these more complex, could we maybe pass the `filepath_container` as an argument for the `migrate` method and keep the implementation in `PsqlDosBackend`?

Don't think this will work because if you look at the code, it is not just in `Migrator.migrate` that the path it is needed. It is actually retrieved in various places through the migrator instance that is passed around. Not sure if that would make it any cleaner.

2022-05-16 08:44 UTC, ramirezfranciscof commented
Right, I was not suggesting you do the refactoring now, but perhaps it would be a good time to open an issue documenting a bit the intricacy of the problem since you have just clashed with it and have the details fresh in your head.

In any case, I think I'll remove myself from the reviewers because it seems a lot of contextual information about these classes is needed to do a good review of the changes.

2022-05-16 09:05 UTC, chrisjsewell requested changes
Sorry, but there is no way I'm excepting this in the current form.
Among other things, make `filepath_container` a static/standalone function, there is absolutely no need for it to be dependent on instances of the `Migrator` or `StorageBackend`, it only depends on the profile

2022-05-16 09:57 UTC, sphuber commented
> Among other things, make `filepath_container` a static/standalone function, there is absolutely no need for it to be dependent on instances of the `Migrator` or `StorageBackend`, it only depends on the profile

How so? Its implementation comes from the `PsqlDosBackend` so why doesn't it make sense to have it be a method on that class?

2022-05-16 12:18 UTC, chrisjsewell commented
> so why doesn't it make sense to have it be a method on that class?

Because you are massively overcomplicating a simple function that turns a string into a path, and passing around classes where they don't need to be passed

2022-05-17 18:38 UTC, sphuber commented
There @chrisjsewell I have turned it into a function. Should be good now

2022-07-08 11:58 UTC, sphuber commented
Want to still review this @chrisjsewell ? Otherwise I'll merge it

2022-07-13 08:33 UTC, giovannipizzi approved these changes
This now seems OK to me!

2022-07-14 16:51 UTC, chrisjsewell approved these changes
Thanks @sphuber, this looks much better, just one nitpick

2022-07-14 16:51 UTC, chrisjsewell commented on aiida/storage/psql_dos/backend.py
> +def get_filepath_container(profile) -> pathlib.Path:
```suggestion
def get_filepath_container(profile: Profile) -> pathlib.Path:
```

2022-07-14 19:04 UTC, merged