Not prompt memory set for core.direct
aiidateam/aiida-core pull request #5642
Opened 2022-09-15 15:35 UTC by unkcpz

The warning `Warning: Physical memory limiting is not supported by the direct scheduler.` pop up if set the computer by interactive mode. 
The `default_memory_per_machine` should not pop up from computer setup with `core.direct` scheduler.

But I am not sure where to add the unit test for this.

2022-09-15 16:04 UTC, sphuber requested changes
Thanks @unkcpz . As for the testing, I would add it to `tests/cmdline/commands/test_computer.py`. Run a setup command with `--scheduler-type=core.direct` and make sure that the warning from the `DirectJobResource` is not printed. There might be a more robust way that would monkeypatch either the option or the command to raise when it is called or the option is specified in the command.

2022-09-18 07:56 UTC, unkcpz commented on aiida/schedulers/datastructures.py
> +    def accepts_default_memory_per_machine(cls):
Fully agree, the potential risk you mentioned is true, I found I missing to implement the abstract method to `TemplateJobResource`.

2022-09-18 08:41 UTC, unkcpz commented
@sphuber thanks! I add the test in `tests/cmdline/commands/test_computer.py` change the test name from `test_interactive` to `test_direct_interactive` and pop the unused `default-memory-per-machine` from the options list. 
The test passes with the current implementation as expectation and fails the previous which stuck at asking for the `default-memory-per-machine`.

2022-09-20 09:32 UTC, sphuber commented
@unkcpz if you fix the tests and docs, I will give another review

2022-09-20 11:31 UTC, sphuber approved these changes

2022-09-20 11:31 UTC, merged

2022-09-20 11:32 UTC, sphuber commented
thanks @unkcpz

2022-09-20 11:32 UTC, unkcpz commented
Thanks @sphuber, I forget to request for your review again 😆