CVE-2007-4559 Patch
aiidateam/aiida-core pull request #5681
Opened 2022-10-03 09:11 UTC by TrellixVulnTeam

# Patching CVE-2007-4559

Hi, we are security researchers from the Advanced Research Center at [Trellix](https://www.trellix.com). We have began a campaign to patch a widespread bug named CVE-2007-4559. CVE-2007-4559 is a 15 year old bug in the Python tarfile package. By using extract() or extractall() on a tarfile object without sanitizing input, a maliciously crafted .tar file could perform a directory path traversal attack. We found at least one unsantized extractall() in your codebase and are providing a patch for you via pull request. The patch essentially checks to see if all tarfile members will be extracted safely and throws an exception otherwise. We encourage you to use this patch or your own solution to secure against CVE-2007-4559. Further technical information about the vulnerability can be found in this [blog](https://www.trellix.com/en-us/about/newsroom/stories/research/tarfile-exploiting-the-world.html).

If you have further questions you may contact us through this projects lead researcher [Kasimir Schulz](mailto:kasimir.schulz@trellix.com).

2022-10-03 12:11 UTC, sphuber requested changes
Thanks @TrellixVulnTeam for notifying us of the vulnerability. Not sure if you are monitoring these PRs since they seem heavily (and understandibly) automated, but we need some changes before we can merge. Changing the exception type is minor, but the invocation of `extractall` is actually incorrect and was caught by our unit tests.

2022-10-03 12:11 UTC, sphuber commented on aiida/storage/sqlite_zip/migrations/legacy_to_main.py
> +                    tar.extractall(path, members, numeric_owner)
According to the [official docs](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall) `numeric_owner` is a keyword-only argument.
```suggestion
                    tar.extractall(path, members, numeric_owner=numeric_owner)
```

2022-10-03 12:11 UTC, sphuber commented on aiida/storage/sqlite_zip/migrations/legacy_to_main.py
> +                import os
```suggestion
                import os
                from aiida.tools.archive.exceptions import ArchiveImportError
```

2022-10-03 12:11 UTC, sphuber commented on aiida/storage/sqlite_zip/migrations/legacy_to_main.py
> +                            raise Exception('Attempted Path Traversal in Tar File')
```suggestion
                            raise ArchiveImportError('Attempted Path Traversal in Tar File')
```

2022-10-05 08:50 UTC, sphuber approved these changes

2022-10-05 08:53 UTC, merged

2022-10-05 08:53 UTC, sphuber commented
Thanks @TrellixVulnTeam

2022-10-07 03:50 UTC, dottereldesign commented
> Thanks @TrellixVulnTeam for notifying us of the vulnerability. Not sure if you are monitoring these PRs since they seem heavily (and understandibly) automated, but we need some changes before we can merge. Changing the exception type is minor, but the invocation of `extractall` is actually incorrect and was caught by our unit tests.

Hey mate, they are automated and malicious. Block them.