Docs: Notify that an entry point is required for creating a data plugin
aiidateam/aiida-core pull request #5907
Opened 2023-02-26 17:58 UTC by AhmedBasem20

Fixes #5456

2023-03-03 14:25 UTC, sphuber requested changes
Thanks @AhmedBasem20 . Small suggestion for the phrasing and a fix for the link syntax, which was incorrect

2023-03-03 14:25 UTC, sphuber commented on docs/source/topics/data_types.rst
> +    You must register a new data entry point. See `aiida.data <https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#aiida-data>`
```suggestion
    To be able to use the new ``Data`` plugin, it must be registered using an entry point.
    See :ref:`What is an entry point?<topics:plugins:entrypoints>` for details.
```

2023-03-03 15:59 UTC, AhmedBasem20 commented
Thanks @sphuber for reviewing. The suggested changes are updated.

2023-03-04 13:47 UTC, sphuber commented on docs/source/topics/data_types.rst
> +	    See :ref:`What is an entry point?<topics:plugins:entrypoints>` for details.
```suggestion
    To be able to use the new ``Data`` plugin, it must be registered using an entry point.
    See :ref:`What is an entry point?<topics:plugins:entrypoints>` for details.
```

2023-03-04 14:02 UTC, sphuber approved these changes

2023-03-04 14:02 UTC, merged