CI Workflow: Update sphinx-intl new release & Install Transifex CLI.
aiidateam/aiida-core pull request #5908
Opened 2023-02-27 09:10 UTC by AhmedBasem20

CLoses #5748 

The new sphinx-intl release (2.1.0) is now updated, Also Transfix CLI installation script has been added.

2023-03-06 10:53 UTC, unkcpz requested changes
Thanks for the contribution @AhmedBasem20,  just one minor request. Can you also add a version for the transifex cli as mentioned in https://github.com/transifex/cli#installing-with-a-script-linuxmac? 

I think there is some problem on my initial implementation, since I now realize it is not a good practice to push to transifex when new version released. The documentation `.pot` files need to updated when there are new changes in `/doc` folder in the main branch, which will make the `latest` of other language versions of documentation synchronize with the latest official version. 
But nothing related to this PR, and I'll leave it to myself in the future.

2023-03-06 10:59 UTC, unkcpz commented on .github/workflows/post-release.yml
> +        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
```suggestion
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash -s -- v1.6.5
```

2023-03-06 14:54 UTC, AhmedBasem20 commented
Thanks @unkcpz for reviewing. I added the requested transifex cli version. Your insight on best practices is greatly appreciated. Thanks again for your time and guidance!

2023-03-10 17:24 UTC, unkcpz approved these changes
Thanks @AhmedBasem20. I give it a local test, all good!

2023-03-17 09:52 UTC, merged