Update tutorial.md on links about "entry point" and "plugin"
aiidateam/aiida-core pull request #6095
Opened 2023-08-08 15:41 UTC by Clarkszw

2023-08-12 00:21 UTC, unkcpz requested changes
Thanks @Clarkszw I have some minor requests. But I have to admit I also not very satisfied with my expression 😬 Better have others have another eye on it.

2023-08-12 00:21 UTC, unkcpz commented on docs/source/intro/tutorial.md
> +to show the available pulgins and their entry points.
this command only shows the entry points groups, it'll be better to elaborate a bit and provide an example of `verdi plugin list aiida.workflows core.arithmetic.multiply_add`.

2023-08-12 00:21 UTC, unkcpz commented on docs/source/intro/tutorial.md
> +A plugin can extend the functionality of AiiDA. Check out [How to install plugins](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugins_install.html)
```suggestion
The plugin extend the functionality of AiiDA. There are many ready to sue plugins can be found in [AiiDA registry](https://aiidateam.github.io/aiida-registry/). Please check out [how to install plugins](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugins_install.html)
```

2023-08-12 00:21 UTC, unkcpz commented on docs/source/intro/tutorial.md
> +Further reading [How to write a plugin for an external code](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugin_codes.html#).
```suggestion
If you can not find the plugins that fulfill your tasks, you may want to create your own plugins. Then please check [how to write a plugin for an external code](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugin_codes.html#).
```

2023-08-12 00:21 UTC, unkcpz commented on docs/source/intro/tutorial.md
> +In AiiDA, an [entry point](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#topics-plugins-entrypoints) is a way to specify and register a plugin or code so that it can
```suggestion
The [entry point](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#topics-plugins-entrypoints) is a way to make it easily access a core or user-defined AiiDA object and make the AiiDA objects discoverable. 
```

2023-08-12 00:27 UTC, unkcpz requested changes

2023-08-12 00:27 UTC, unkcpz commented on docs/source/intro/tutorial.md
> +In AiiDA, an [entry point](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#topics-plugins-entrypoints) is a way to specify and register a plugin or code so that it can
I'd also prefer this is not as a "Note", it just has too many "Note" in this section, and it is not something the reader need to note but more like detailed declarative information.

2023-08-12 17:38 UTC, ltalirz commented on docs/source/intro/tutorial.md
> +The `WorkflowFactory` is a useful and robust tool for loading workflows based on their [*entry point*](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#topics-plugins-en
```suggestion
The `WorkflowFactory` loads workflows based on their [*entry point*](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#topics-plugins-entrypoints), e.g. `'core.arithmetic.multiply_add'` in this case.
The entry point mechanism allows AiiDA to discover workflows provided not just by  ``aiida-core`` but by plugins as well.
```

2023-08-12 17:38 UTC, ltalirz commented on docs/source/intro/tutorial.md
> +In AiiDA, an [entry point](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/plugins.html#topics-plugins-entrypoints) is a way to specify and register a plugin or code so that it can
```suggestion
```

2023-08-12 17:45 UTC, ltalirz commented on docs/source/intro/tutorial.md
> +To simplify the basic tutorial, we have left out the steps to register the `MultiplyAddWorkChain` as a plugin which allows us to access the class through the [*entry point*](https://aiida.readthedocs
This is adding the information twice. I would suggest to remove this and mention entry points only after they are used (below)

2023-08-12 17:46 UTC, ltalirz commented on docs/source/intro/tutorial.md
> +The entry point mechanism allows AiiDA to automatically discover workflows provided not by  `aiida-core` and installed [*plugins*](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plu
```suggestion
The entry point mechanism allows AiiDA to automatically discover workflows provided by  `aiida-core` and [*AiiDA plugins*](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugins_install.html)) and display them to the user, e.g. via `verdi plugin list aiida.workflows`.
```

2023-08-12 17:47 UTC, ltalirz commented on docs/source/intro/tutorial.md
> +A plugin can extend the functionality of AiiDA. Check out [How to install plugins](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugins_install.html)
```suggestion
```

2023-08-12 17:52 UTC, ltalirz commented on docs/source/intro/tutorial.md
> +
```suggestion
```

2023-08-12 17:53 UTC, ltalirz requested changes
thanks @Clarkszw :-) !

I've made some changes; from my side it looks good now.

Could you please replace the internal links with references (just have a look at other references on how to do this). Thanks!

2023-08-13 07:39 UTC, Clarkszw commented
> Thanks!

Yes, would love to do. But could you explain me about 'replacing  the internal links with references'?
Do you mean the `#` after the link? (I think they have). Or other reference section that I can update?

2023-08-14 12:21 UTC, ltalirz approved these changes
Looks good to me now

2023-08-19 07:05 UTC, merged