Fix timeout in process actions
aiidateam/aiida-core pull request #6203
Opened 2023-12-04 15:25 UTC by superstar54

Issue: My terminal hangs when I run `verdi process play pk` for an unreachable process.

Reason:
When a future is finished, it can be `done` or `excepted`. If the future is excepted, one will wait forever using `future.result()`.
Also, it is good to add timeout in the `exception` and `result`.

2023-12-06 08:05 UTC, sphuber requested changes
Could you please add a test for this. You would have to create a process without the task being sent to RabbitMQ. You can see an example of how to do this in `tests/engine/processes/test_control.py` in the `test_revive` test:
```python

    # Temporarily patch the ``RemoteProcessThreadController.continue_process`` method to do nothing and just return a
    # completed future. This ensures that the submission creates a process node in the database but no task is sent to
    # RabbitMQ and so the daemon will not start running it.
    with monkeypatch.context() as context:
        context.setattr(RemoteProcessThreadController, 'continue_process', lambda *args, **kwargs: None)
        node = submit(builder)
```
you can then call `_resolve_futures` (or whatever the parent function is) with a timeout and check that it indeed timesout.

2023-12-06 08:05 UTC, sphuber commented on aiida/engine/processes/control.py
> +#pylint: disable=too-many-branches
This is now actually disabling for all of the rest of the file. You should move it next to the function definition, e.g.
```python
def _resolve_futures(  # pylint: disable=too-many-branches
```

2024-01-31 08:06 UTC, sphuber commented
@superstar54 what is the plan for this PR? Do you still want to have a look at adding a test?

2024-02-23 08:15 UTC, sphuber commented
pinging @superstar54

2024-03-07 11:24 UTC, superstar54 commented
@sphuber, I did some tests and found the original code handles the timeout correctly. And I don't remember how to reproduce the error. So I am closing this PR now and will reopen it when I encounter the issue again.

2024-03-07 11:24 UTC, closed without merging