Refactor: Abstract message broker functionality
aiidateam/aiida-core pull request #6303
Opened 2024-03-02 22:19 UTC by sphuber

RabbitMQ is used as a message broker to allow processes to be distributed across multiple daemon workers. Setting up RabbitMQ as a service can be a hurdle for users and for simple use cases the additional scaling it provides is not always necessary.

The idea is to provide a light version of AiiDA that doesn't require a message broker, making it easy to setup and install to allow users to quickly familiarize themselves with AiiDA before committing to a more production ready setup.

Currently, the RabbitMQ functionality is a bit dispersed throughout the codebase, making it difficult to make its use optional. Therefore, the first step is to refactor the code and centralize all RabbitMQ specific functionality.

The `aiida.brokers` module is introduced, which provides the abstract class `Broker`. This is the interface that a message broker, such as RabbitMQ should implement. The existing RabbitMQ implementation is added to the `RabbitmqBroker` class.

The `Manager` class now provides the `get_broker` method which will load the broker instance based on the plugin that is defined by the profile. This is an entry point that should be registered in the `aiida.brokers` group.

For now, a `NocommsBroker` is implemented which should serve the case when no message broker is available or needed. It is not quite sure if the alternative of just having `Manager.get_broker` returning `None` would be simpler and ultimately better.

These changes are just a first refactoring that don't change any functionality and everything is backwards compatible. In the future, functionality can be added to allow creating profiles that do not define a broker. These can then be used to run processes locally in the same Python interpreter in which they are launched.

2024-03-13 21:08 UTC, sphuber commented
@edan-bainglass @unkcpz There is a problem with the tests you added for the `aiida-core-dev` Docker image recently. The problem is that it checks out the default branch of the main repository and so tests are run against that. However, they should really be run against the branch of the PR. I needed to change the tests since part of the functionality they test changes in this PR. How can we fix this? Can we make the remote and branch that is checked out for the tests configurable somehow?

2024-03-14 03:06 UTC, unkcpz commented
Hi @sphuber, true, that is a problem. I think the proper way is instead of clone the repo, in the dockerfile we copy the aiida-core src to the container.

2024-03-14 03:12 UTC, unkcpz commented
I open a PR to try to address the issue https://github.com/aiidateam/aiida-core/pull/6314

2024-03-14 06:49 UTC, sphuber commented
> I open a PR to try to address the issue #6314, can you rebase this PR to test if it works?

Seems to do the trick, thanks! I will merge the other PR

2024-03-14 08:18 UTC, sphuber commented
@unkcpz would you perhaps have the time to have a look at this PR? Don't worry about the separate commits. Just look at the total changes. I just added the second commit in case I need to revert, but I don't think we will. I think the current solution (without dummy `NoCommsBroker` plugin for profiles without a broker, and just have `Manager.get_broker()` return `None`) is better.

2024-03-14 15:36 UTC, giovannipizzi commented
Really cool and useful, thanks @sphuber! Is there already documentation of the API of the Broker class, i.e. what functionality one needs to implement if I want to provide a different broker, what are the requirements of the Broker, etc?

2024-03-14 16:21 UTC, sphuber commented
> Really cool and useful, thanks @sphuber! Is there already documentation of the API of the Broker class, i.e. what functionality one needs to implement if I want to provide a different broker, what are the requirements of the Broker, etc?

Not yet. This would require more work and I would prefer not to have that block this, because the most important reason for this work is to enable service-less profile. The fleshing out of the broker interface will require a lot more work. This is also the reason why I wouldn't officially document it _yet_, because likely we will have to improve/change this in the future once we figure out what the correct abstract interface should be.

2024-03-15 06:31 UTC, edan-bainglass commented
> @edan-bainglass @unkcpz There is a problem with the tests you added for the `aiida-core-dev` Docker image recently. The problem is that it checks out the default branch of the main repository and so tests are run against that. However, they should really be run against the branch of the PR. I needed to change the tests since part of the functionality they test changes in this PR. How can we fix this? Can we make the remote and branch that is checked out for the tests configurable somehow?

I just tested on my end. I ran the docker tests on `main` (with @unkcpz's recent "fix" PR), and then with my `entity-fields` PR on top of it. In both cases, the tests failed with a `TCP connection closed`. However, simply rerunning the tests pushed through and finished successfully. Not great!

Note that for @sphuber, the tests appear to fail at the `aiida-core-dev` stage. However, in my case, they were already failing at the `aiida-core-base` stage, so this is perhaps a bigger issue. @unkcpz can we look into this? Also, @unkcpz, I'm unclear as to how your PR fixes the issue mentioned by @sphuber, i.e. tests running against the wrong branch. Is it not possible to fix this with the clone approach? Just checkout the PR branch pre-test stage?

2024-03-15 08:36 UTC, sphuber commented
>  Is it not possible to fix this with the clone approach?

Then you would have to start figuring out in the script itself what fork and branch the PR is coming from. If that is even possible, it is unnecessarily complicated right, because you _have_ the correct code checked out locally by definition when you run the build.

> In both cases, the tests failed with a TCP connection closed. However, simply rerunning the tests pushed through and finished successfully. Not great!

Can you give more information on the exact error? Was there an exception? What is the stack trace? Where is the error coming from? And I see now on your PR that the build passed. Did you just restart the failed build, and the second time around it passed? Is that what you mean, that the problem seems transient?

2024-03-15 11:34 UTC, edan-bainglass commented
> > Is it not possible to fix this with the clone approach?
> 
> Then you would have to start figuring out in the script itself what fork and branch the PR is coming from. If that is even possible, it is unnecessarily complicated right, because you _have_ the correct code checked out locally by definition when you run the build.

Thanks @sphuber for clarifying. I understand now how copying the local code (which is in the PR branch) fixes this issue.

> 
> > In both cases, the tests failed with a TCP connection closed. However, simply rerunning the tests pushed through and finished successfully. Not great!
> 
> Can you give more information on the exact error? Was there an exception? What is the stack trace? Where is the error coming from? 

I attempted to reproduce the issue a few times. Of course, it now passes every time. Nevertheless, here's an excerpt:

![image](https://github.com/aiidateam/aiida-core/assets/45081142/19233f99-b643-4138-aab1-e1ae482cb54d)

See the `role "root" does not exist` followed by a closing of the TCP connection? The test got stuck there. It just reattempted that part over and over until it timed out. At least that's what it seems to be doing.

> And I see now on your PR that the build passed. Did you just restart the failed build, and the second time around it passed? Is that what you mean, that the problem seems transient?

Yes, once I noticed that locally it failed, but then passed, I reran the test on my PR, which passed. No change introduced!

2024-03-18 19:10 UTC, unkcpz requested changes
Very cool, thanks @sphuber! Apparently you find another layer of abstraction. 
I only have two small questions, if you can further explain those.

2024-03-18 19:10 UTC, unkcpz commented on src/aiida/manage/manager.py
> +            # Backwards compatibility. Before adding broker entry points, profiles used to define ``rabbitmq``.
I didn't get this, where was the ``rabbitmq`` originally defined?

2024-03-18 19:22 UTC, sphuber commented on src/aiida/brokers/broker.py
> +        """Return an instance of :class:`kiwipy.Communicator`."""
For now, a new broker implementation would indeed have to implement the `kiwipy.Communicator` interface. For now, I just did the minimal changes necessary to abstract the broker. This is not so much to make it possible to provide other broker implementations, but really to make it easy to run AiiDA with _no_ broker at all. I thought that abstracting the functionality in this way made it as easy as possible to accomplish that.

As I mentioned [in this comment](https://github.com/aiidateam/aiida-core/pull/6303#issuecomment-1997839409) actually fully abstracting the broker/communicator interface would take more work, but is not the main goal here.

2024-03-18 19:23 UTC, sphuber commented
> Very cool, thanks @sphuber! Apparently you find another layer of abstraction.

Hehe yeah 😅 I was really hoping not to have to do that, but it seems the best option to allow running AiiDA in minimal mode that doesn't require RabbitMQ.

2024-03-18 19:40 UTC, unkcpz approved these changes
Looks all good, I'll give it a more close test on PR `verdi blitz`.

2024-03-20 08:55 UTC, merged