BaseRestartWorkChain: fix handlers overrides
aiidateam/aiida-core pull request #6308
Opened 2024-03-06 13:56 UTC by yakutovicha

fixes #6307 

It turns out that the issue was in the `get_process_handlers_by_priority` method. When running `enabled = overrides.get('enabled')` the original dictionary would be overridden by the `pop` method for the next iteration would be empty.

I tested the updated version of the work chain, and the issue was fixed for me locally.

2024-03-06 20:16 UTC, sphuber requested changes
Thanks @yakutovicha . The change makes sense. Could you please add a unit test for this in `tests/engine/processes/workchains/test_restart.py`? Essentially you would just create a `BaseRestartWorkChain` instance with a number of handler overrides as input, and then you call `get_process_handlers_by_priority` twice in a row, making sure it return the same and correct dictionary each time.

2024-03-20 08:51 UTC, sphuber commented
@yakutovicha the following patch adds a regression test. Could you please add that to your branch:
```diff
diff --git a/tests/engine/processes/workchains/test_restart.py b/tests/engine/processes/workchains/test_restart.py
index 7518b7d7a..02627615e 100644
--- a/tests/engine/processes/workchains/test_restart.py
+++ b/tests/engine/processes/workchains/test_restart.py
@@ -72,7 +72,8 @@ def test_get_process_handlers_by_priority(generate_work_chain, inputs, prioritie
         warnings.simplefilter('ignore')
         process = generate_work_chain(SomeWorkChain, inputs)
     process.setup()
-    assert sorted([priority for priority, handler in process.get_process_handlers_by_priority()]) == priorities
+    handlers = process.get_process_handlers_by_priority()
+    assert sorted([priority for priority, _ in handlers]) == priorities
 
     # Verify the actual handlers on the class haven't been modified
     assert getattr(SomeWorkChain, 'handler_a').priority == 200
@@ -82,6 +83,14 @@ def test_get_process_handlers_by_priority(generate_work_chain, inputs, prioritie
     assert getattr(SomeWorkChain, 'handler_b').enabled
     assert not getattr(SomeWorkChain, 'handler_c').enabled
 
+    # Validate that a second invocation return the exact same results. This is a regression test for
+    # https://github.com/aiidateam/aiida-core/issues/6307. Note that the handlers are compared by name, because the
+    # bound methods will be separate clones and the ``__eq__`` operation will return ``False`` even though it represents
+    # the same handler function.
+    assert [(p, h.__name__) for p, h in process.get_process_handlers_by_priority()] == [
+        (p, h.__name__) for p, h in handlers
+    ]
+
 
 @pytest.mark.requires_rmq
 def test_excepted_process(generate_work_chain, generate_calculation_node):
```
Then we can merge this PR. Thanks

2024-03-22 13:54 UTC, sphuber approved these changes

2024-03-22 13:54 UTC, merged

2024-03-24 20:04 UTC, yakutovicha commented
sorry, @sphuber, I went on vacation and wasn't working

2024-03-25 08:14 UTC, sphuber commented
No worries, since it was just a chore of adding the test, I figured I'd pitch in. Hope you don't mind and you had a good vacation