CLI: minor change on `verdi plugin list` logic to show description
aiidateam/aiida-core pull request #6411
Opened 2024-05-22 10:32 UTC by khsrali

If a plugin that is not a `Process` but hasn't set `plugin.is_process_function=False` supports `get_description()`
 `aiida-core` should understand in this scenario, `plugin.is_process_function` is obviously `False`.
Currently, `AttributeError` could get caught by not having `is_process_function` instead of `get_description()`

2024-05-23 07:53 UTC, khsrali commented
> I don't understand the problem from your description to be honest. Could you please provide an example where this failed? It would anyway be good to add that as a regression test.

Alright, I try to improve the description:

Suppose you write a plugin named X. 

```python
Class X(Transport):
    ..
    @classmethod
    def get_description(cls) -> str:
         return "I'm  X"
    ..
```

Once the plugin is installed, try `verdi plugin list aiida.transports X`

What you get is:
`Error: No description available for X`

Which means [this AttributeError](https://github.com/aiidateam/aiida-core/blob/22ea06362e9de5d314f103332da2e25ae6080f61/src/aiida/cmdline/commands/cmd_plugin.py#L55) was handled only because `is_process_function` was not found in the plugin, despite the existence of `get_description`.


I agree, it would be great to write a test for this, but one has to know how to mock a plugin, which I don't.
Do we have a fixture for that? I would appreciate any hint.
Thank you,

2024-05-23 09:54 UTC, sphuber commented
> Which means [this AttributeError](https://github.com/aiidateam/aiida-core/blob/22ea06362e9de5d314f103332da2e25ae6080f61/src/aiida/cmdline/commands/cmd_plugin.py#L55) was handled only because `is_process_function` was not found in the plugin, despite the existence of `get_description`.

Thanks, I understand now. I missed this because I thought the conditional had _and_ instead of _or_ and so I mistakenly thought that if the plugin was not a process, it would have been caught by the first part of the conditional and woulnd't even get to the `plugin.is_process_function`.

Now that we understand that though, a better solution is not to just broadly catch this `AttributeError` but more explicitly defend against this in the conditional. So I would propose instead
```python
if (inspect.isclass(plugin) and issubclass(plugin, Process)) or hasattr(plugin, 'is_process_function'):
```

> I agree, it would be great to write a test for this, but one has to know how to mock a plugin, which I don't. Do we have a fixture for that? I would appreciate any hint.

https://aiida.readthedocs.io/projects/aiida-core/en/stable/topics/plugins.html#topics-plugins-testfixtures-entry-points

2024-05-23 14:56 UTC, sphuber commented
There are more problems with the example. The assert statement also doesn't make sense. It should be
```python
assert ParserFactory('test') is CustomParser
```
and then the final problem is that the `CustomParser` should be defined on the module level. Like it is currently, defined in the local scope of the test function, the factory will not be possible to load it. So the correct version is
```python
from aiida.parsers import Parser

class CustomParser(Parser):
    """Parser implementation."""


def test_parser(entry_points):
    """Test a custom ``Parser`` implementation."""
    from aiida.plugins import ParserFactory

    entry_points.add(CustomParser, 'aiida.parsers:custom.parser')

    assert ParserFactory('custom.parser') is CustomParser
```

I will submit a PR to fix the docs.

2024-05-23 15:02 UTC, sphuber commented
https://github.com/aiidateam/aiida-core/pull/6412

2024-05-23 16:57 UTC, sphuber requested changes
Thanks @khsrali just a few minor corrections

2024-05-23 16:57 UTC, sphuber commented on tests/cmdline/commands/test_plugin.py
> +    assert result.stdout_bytes.decode('utf-8').strip() == 'str69'
```suggestion
    assert result.output.strip() == 'str69'
```

2024-05-23 16:57 UTC, sphuber commented on tests/cmdline/commands/test_plugin.py
> +    """Test if `verdi plugin list` would show description of an external plugin."""
```suggestion
    """Test that ``verdi plugin list`` uses ``get_description`` if defined."""
```

2024-05-23 16:57 UTC, sphuber commented on src/aiida/cmdline/commands/cmd_plugin.py
> +                ):
This phrasing with a nested `if` feels a bit awkward. I think a more typical formulation would be
```suggestion
                if (inspect.isclass(plugin) and issubclass(plugin, Process)) or (
                    hasattr(plugin, 'is_process_function') and plugin.is_process_function
                ):
```

2024-05-23 21:02 UTC, sphuber approved these changes
Thanks a lot @khsrali

2024-05-23 21:03 UTC, merged

2024-08-14 14:15 UTC, edan-bainglass commented
Hmm, not sure if related to this PR, but I now get the following on `verdi plugin list aiida.data core.array`
```
Traceback (most recent call last):
  File "/opt/conda/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/aiida/cmdline/commands/cmd_plugin.py", line 56, in plugin_list
    echo.echo(str(plugin.get_description()))
TypeError: get_description() missing 1 required positional argument: 'self'
```
Happens with a few (if not all) data entry points.

v2.6.2

2024-08-14 20:30 UTC, sphuber commented
It is in fact related to this PR. The PR fixed a bug where the conditional would always raise an `AttributeError` for non-process plugins and so would always skip and simply print that no description was available. After this fix, the code now actually goes to the else-clause and calls `plugin.get_description`, but this is _also_ a bug that simply was always hidden by the first bug. The `get_description` method is an instance method and the `plugin` is a class, so that call fails. There is no `get_description` classmethod though that provides a description of the plugin. The best we can do I think is to simply display the docstring of the plugin