Adapt message arguments passing to process controller
aiidateam/aiida-core pull request #6668
Opened 2024-12-16 14:28 UTC by unkcpz

Changes required after https://github.com/aiidateam/plumpy/pull/301 and https://github.com/aiidateam/plumpy/pull/291

2024-12-16 15:34 UTC, khsrali requested changes
Thanks a lot @unkcpz , I have just one comment.

2024-12-17 15:04 UTC, khsrali reviewed
@unkcpz thanks a lot! changes makes sense. 
As agreed let's wait for a `plumpy` release before merging this. and we have to remember to remove the commit hook for `plumpy` so to pin the to-be-released version.

2025-01-07 10:15 UTC, agoscinski reviewed
Looks okay, just needs to be rebased after plumpy release

2025-01-08 15:36 UTC, unkcpz commented on src/aiida/engine/processes/control.py
> +            future = action(process.pk)
Good point, I just remove the use of `kwargs`.

2025-01-08 17:04 UTC, unkcpz commented
@khsrali I rebase with the main branch of plumpy, all tests are passed. We can make a release for plumpy.

2025-01-10 13:47 UTC, unkcpz commented
Hi @khsrali, I update plumpy version, should all good now. Can you have another look?

2025-01-10 21:45 UTC, unkcpz commented
I'll merge this now, it blocks my work on https://github.com/aiidateam/aiida-core/pull/6675. The changes here are mostly variable names of function call. 
In https://github.com/aiidateam/aiida-core/pull/6675, there are other engine changes that are hard to debug (I was struggle on things are working on python3.12 but not python3.9) I want to isolate the changes from this PR.

Free free to comment on the PR and I 'll add amend changes if needed.

2025-01-13 15:46 UTC, merged