WIP: Update uv.lock + CI tweaks
aiidateam/aiida-core pull request #6676
Opened 2024-12-29 19:00 UTC by danielhollas

2024-12-30 22:27 UTC, danielhollas commented
There's one failing test in test-install with Python 3.9, due to https://github.com/astral-sh/setup-uv/issues/219

```
        # In Cygwin paths like "c:\..." and '\cygdrive\c\...' are possible
>       if p_venv.parts[1] == "cygdrive":
E       IndexError: tuple index out of range

.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:890: IndexError
========================================================== slowest 50 durations ===========================================================

(3 durations < 1s hidden.  Use -vv to show these durations.)
========================================================= short test summary info =========================================================
FAILED tests/tools/ipython/test_ipython_magics.py::test_ipython_magics - IndexError: tuple index out of range
```

2024-12-30 23:14 UTC, danielhollas commented on .github/workflows/ci-code.yml
> -      run: source .venv/bin/activate && .github/workflows/setup.sh
The updated setup-uv action now activates the virtual environment automatically.

2025-01-07 13:42 UTC, danielhollas commented
@unkcpz @agoscinski this is now ready for review, please take a look, I've written an extended PR description, let me know if anything is not clear. Note in particular:

> For Python 3.9, I added a workaround suggested in https://github.com/materialsproject/pymatgen/issues/4243#issuecomment-2573310051, and unset the CI environmental variable.
Since this woraround is quite targeted (only in two specific job steps, and only for Python 3.9), I believe this is acceptable, and we will be dropping Python 3.9 support sometimes this year anyway.

Regardless if we decide if this is a good solution or not, I think this PR should go in first before #6680 since it fixes the pymatgen issue for everything except Python 3.9.

2025-01-07 13:54 UTC, danielhollas commented on .github/actions/install-aiida-core/action.yml
> -    run: uv sync --locked --extra pre-commit
Previously we were not respecting the `inputs.extras` when using the lockfile. Now we do (at the expense of very ugly Github Actions syntax :-( )

2025-01-07 13:55 UTC, danielhollas commented on .github/actions/install-aiida-core/action.yml
> -    run: uv pip install --system -e .${{ inputs.extras }}
Since now `setup-uv` action activates the virtual environment automatically, we no longer need to install into system python.

2025-01-07 13:56 UTC, danielhollas commented on .github/workflows/ci-code.yml
> +      # TODO: Remove a workaround for VIRTUAL_ENV once the setup-uv action is updated
This issue is described in detail in https://github.com/aiidateam/aiida-core/pull/6676#issuecomment-2565971534.

I'll remove the workaround hopefully soon in a subsequent PR.

2025-01-07 13:57 UTC, danielhollas commented on .github/workflows/test-install.yml
> +      run: uv lock --check
The `--check` option is a new alias for `--locked` which is more intuitive.

2025-01-07 16:57 UTC, rabbull commented on .github/workflows/ci-code.yml
> +        ${{ matrix.python-version == '3.9' && 'unset CI' || '' }}
Yeah you got a point. Your solution looks perfectly good to me. Let's wait the maintainers check look this PR up and get it merged.

2025-01-08 08:45 UTC, agoscinski requested changes
Looks good to me, just need some clarifications with some changes

2025-01-08 08:45 UTC, agoscinski commented on .github/actions/install-aiida-core/action.yml
> -    run: uv sync --locked --extra pre-commit
I think it is inspired from JavaScript so at least not completely random.

2025-01-08 08:45 UTC, agoscinski commented on .github/workflows/test-install.yml
> +  FORCE_COLOR: 1
Why this has to be added in this PR? I just don't see anything related to it. Is it just to ensure that colors are used for visuals? I am asking because I remember that some tests rely on the color and fail when playing with these options but I don't remember the details anymore.

2025-01-08 08:45 UTC, agoscinski commented on .github/workflows/ci-code.yml
> +        # the 'tui' extra is installed.
This appears now because with the changes in the `install-aiida-core` we install all extras? Isn't this something we should fix later on?

2025-01-08 08:48 UTC, unkcpz approved these changes
> In the new uv version, this is not the case, and uv will try to find the newest version of a package for a given python version.

This is nice!

It looks good, thanks @danielholla Just a small question.

2025-01-08 08:48 UTC, unkcpz commented on .github/actions/install-aiida-core/action.yml
> +    default: pre-commit
I am a bit confuse here, how the extra like "atomic_tool" included in pre-commit extra?

2025-01-08 08:48 UTC, unkcpz commented on .github/actions/install-aiida-core/action.yml
> -    run: uv sync --locked --extra pre-commit
~~in CI will `inputs.extras` in `uv sync --locked ${{ inputs.extras && format('--extra {0}', inputs.extras) || '' }}` always be `true`? Because if it is not pass as input it will set to "pre-commit" as default, no? Then this clause can be simplified.~~

Never mind, I see extra='' below.

2025-01-08 08:52 UTC, agoscinski commented on .github/actions/install-aiida-core/action.yml
> +    default: pre-commit
had the same issue last time, because pre-commit depends on them https://github.com/aiidateam/aiida-core/blob/02cbe0ceb7d9f9343911592e31abe6310d2bd38b/pyproject.toml#L214C13-L214C14

2025-01-08 09:23 UTC, danielhollas commented on .github/workflows/test-install.yml
> +  FORCE_COLOR: 1
This is just an unrelated improvement to add colors to pytest output in GitHub UI. 
I am not aware of any tests that would depend on colors, and we're already using this option in many other workflows (e.g. ci-code) so I think this is a safe change.

2025-01-08 10:44 UTC, agoscinski commented on .github/workflows/ci-code.yml
> +        # the 'tui' extra is installed.
Ah sorry for being not clear. I am fine with the changes, just would like to know if we should make an issue and it fix in some later PR

2025-01-08 10:46 UTC, agoscinski commented on .github/workflows/test-install.yml
> +  FORCE_COLOR: 1
There was something that failed in #6434 when I enforced colors but I cannot check it because the CI result already removed it. But when the test pass it should be okay!

2025-01-08 10:47 UTC, agoscinski approved these changes

2025-01-08 10:49 UTC, danielhollas commented on .github/workflows/ci-code.yml
> +        # the 'tui' extra is installed.
I think this is minor enough that it could go in here, but let me know if you disagree.
I can open an issue about converting more CI jobs to use the lockfile though.

2025-01-08 11:23 UTC, agoscinski commented on .github/workflows/ci-code.yml
> +        # the 'tui' extra is installed.
I mean that `verdi devel check-undesired-imports` fails when tui is installed sounds undesirable and sounds like this should be fixed like `only check for asyncio if tui is not installed`. I am not sure why this happens

2025-01-08 11:49 UTC, danielhollas commented on .github/workflows/ci-code.yml
> +        # the 'tui' extra is installed.
Aaah, now I see what you mean. Sorry, I misunderstood your original comment. 
Yeah, I'll open an issue for that.

2025-01-08 13:04 UTC, agoscinski commented
Thanks for the work @danielhollas this was really helpful!

2025-01-08 15:32 UTC, merged

2025-01-08 15:32 UTC, unkcpz commented
Thanks @danielhollas I merge it to not block other PRs on going.

2025-01-09 17:10 UTC, danielhollas commented on .github/workflows/ci-code.yml
> +        # the 'tui' extra is installed.
Opened #6691 to follow up on this

2025-02-08 07:49 UTC, edan-bainglass commented
Hi @unkcpz. Didn't follow this discussion, but I see that it was merged. However, aiida-quantumespresso builds still failing. Can you comment on this briefly?

2025-02-08 11:22 UTC, danielhollas commented
What is the error? I don't think changes in this PR would influence aiida-qe since it doesn't use the uv.lock file. I think the original pymatgen issue is solved by simply bumping the pymatgen version.

2025-02-08 15:56 UTC, unkcpz commented
> However, aiida-quantumespresso builds still failing. Can you comment on this briefly?

The CI seems all passed in aiida-quantumespresso. Which one you mean?